import type { Metadata } from 'next';
import '../globals.css';
import { SidebarInset, SidebarProvider, SidebarTrigger } from '~/components/ui/sidebar';
import { AppSidebar } from '~/components/app-sidebar';
import { Separator } from '~/components/ui/separator';
import { Button } from '~/components/ui/button';
import { logout } from '~/app/actions/auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="flex bg-sidebar h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear">
          <div className="flex items-center justify-between max-w-[90%] w-full">
            <div className="flex items-center gap-2 px-4">
              <SidebarTrigger className="-ml-1 text-sidebar-foreground cursor-pointer" />
              <Separator orientation="vertical" className="mr-2 data-[orientation=vertical]:h-6" />
            </div>
            <div className="flex items-center gap-2 px-4">
              <Button variant="destructive" onClick={logout}>
                Logout
              </Button>
            </div>
          </div>
        </header>
        <main className="min-h-screen">{children}</main>
      </SidebarInset>
    </SidebarProvider>
  );
}
